apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-fe
  labels:
    app: interview-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interview-fe
  template:
    metadata:
      labels:
        app: interview-fe
    spec:
      containers:
        - name: interview-be
          image: 6lackcoder/interview-fe:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          